# Generated by Django 5.1.6 on 2026-09-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=30)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[("stock", "Stock"), ("crypto", "Crypto")],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
