# Generated by Django 5.1.6 on 2026-09-30 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("open_price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("high_price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("low_price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("close_price", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="assets.asset",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("asset", "date"), name="unique_asset_price_date"
                    )
                ],
            },
        ),
    ]
