# Generated by Django 5.2.17 on 2026-10-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
        ("portfolios", "0002_transaction"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["portfolio", "-created_at"], name="portfolio_created_at_idx"
            ),
        ),
    ]
