# Generated by Django 5.2.17 on 2026-10-05 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0003_transaction_portfolio_created_at_idx"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="transaction",
            new_name="portfolio_created_idx",
            old_name="portfolio_created_at_idx",
        ),
    ]
