# Generated by Django 5.2.17 on 2026-10-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0004_rename_portfolio_created_at_idx_portfolio_created_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="idemptotency_key",
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
