# Generated by Django 5.2.17 on 2026-10-07 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0005_transaction_idemptotency_key"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="idemptotency_key",
            new_name="idempotency_key",
        ),
    ]
